const config = {
  $schema: "http://json.schemastore.org/prettierrc",
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: false,
  quoteProps: "as-needed",
  jsxSingleQuote: false,
  trailingComma: "all",
  bracketSpacing: true,
  bracketSameLine: false,
  jsxBracketSameLine: false,
  arrowParens: "always",
  endOfLine: "lf",
  singleAttributePerLine: false,
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  importOrder: [
    "^(react/(.*)$)|^(react$)",
    "<THIRD_PARTY_MODULES>",
    "",
    "^(@pages/(.*)$)|^(@pages$)",
    "",
    "^(@components/(.*)$)|^(@components$)",
    "",
    "^(@store/(.*)$)|^(@store$)",
    "^(@hooks/(.*)$)|^(@hooks$)",
    "^@constants$",
    "^@utils$",
    "",
    "^@types$",
    "",
    "^@images$",
    "^@icons$",
    "^@animations$",
    "",
    "^[./]",
    "",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderBuiltinModulesToTop: true,
};

module.exports = config;
